# Simplified Docker Compose - PostgreSQL only
# Use this if you have network issues with full docker-compose

services:
  # PostgreSQL Database Only
  db:
    image: postgres:15-alpine
    container_name: glynac-postgres
    restart: unless-stopped
    volumes:
      - postgres_data_simple:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: glynac-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "AnjuDevi@#123"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data_simple:
